Exception handling tasks
Task 0: print list safely using exceptions
Task 1: print integer safely using exceptions
Task 2: A function that prints x elements of a list and only integers
Task 3: A function that divides two integers and prints the result
Task 4: A function that divides element by element two lists
Task 5: A function that raises a type exception
Task 6: Raise a name exception with a message
Task 100: A function that prints an integer with a message
Task 101: A function that executes a function safely
